# Bank Churn
  
  <br/><br/>
 

This project aims to identify the most important factors leading to customer churn for a commercial bank.

- 11 tables
- A variety of indexes, primary and foreign key constraints
- Over 15,000 rows of data  


  
Finally, we will export the database tables in **CSV** format, which will be used to create a semantic model in **Power BI** and related dashboards in the next step.  
  
  <br/><br/>

## Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import warnings

In [2]:
# run to avoid warnings
warnings.filterwarnings('ignore')

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('fivethirtyeight')
sns.set(font_scale=0.8)

%config InlineBackend.figure_format = 'retina'
%matplotlib inline

In [5]:
# create a dataframe from CSV
df = pd.read_csv('../data/0-external/Churn_Banking_Modeling.csv', low_memory=False, encoding='latin-1')
df

Id_Cliente Flag_Richiesta_Estinzione_cc  Imp_Valore_del_Cliente  \
0                2                           no                   65.03   
1                3                           no                  138.88   
2                4                           no                  546.54   
3                5                           no                   68.69   
4                7                           no                 2417.05   
...            ...                          ...                     ...   
377364      555146                           no                 5317.47   
377365      555147                           no                   17.35   
377366      555148                           no                  334.73   
377367      555149                           no                 5171.38   
377368      555150                           no                   68.10   

        Flag_Apertura_Conto_Online  Flag_Possesso_piu_Conti   Eta  \
0                                0                        0  38.0   
1                                0                        0  45.0   
2                                0                        0  61.0   
3                                0                        0  33.0   
4                                0                        0  36.0   
...                            ...                      ...   ...   
377364                           1                        0  49.0   
377365                           0                        0  42.0   
377366                           0                        0  54.0   
377367                           0                        0  60.0   
377368                           0                        0  45.0   

       Provincia_Domicilio Provincia_Residenza  Anno_Apertura_primo_Conto  \
0                       BO                  BO                     2004.0   
1                       SA                  SA                     2000.0   
2                       VT                  VT                     2005.0   
3                       MI                  MI                     2010.0   
4                       MI                  MI                     2001.0   
...                    ...                 ...                        ...   
377364                 NaN                 NaN                     2008.0   
377365                  CT                  CT                     2002.0   
377366                  RM                  BZ                     2001.0   
377367                  GE                  GE                     2007.0   
377368                  ME                  ME                     2003.0   

                                      Professione  ... Imp_Liquidità_Attuale  \
0                                       Impiegato  ...               1634.57   
1                                       Impiegato  ...              11918.26   
2                                   Altro/Nessuno  ...               2671.95   
3                                       Impiegato  ...              19211.31   
4                                          Quadro  ...               1526.38   
...                                           ...  ...                   ...   
377364                                   Avvocato  ...              27933.94   
377365                         Docente/Insegnante  ...               -909.87   
377366                          Medico/Farmacista  ...              72535.85   
377367  Libero professionista/Titolare di impresa  ...                115.87   
377368                                  Impiegato  ...                160.82   

       Imp_Gestito_attuale Imp_Amministrato_attuale Imp_Liquidità_Attuale_6m  \
0                  2978.40                  2980.92                  1550.44   
1                      NaN                 34916.15                 26122.17   
2                      NaN                232776.62                 16545.25   
3                 15013.53                 15017.53                 1250

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 377369 entries, 0 to 377368
Data columns (total 43 columns):
 #   Column                               Non-Null Count   Dtype  
---  ------                               --------------   -----  
 0   Id_Cliente                           377369 non-null  int64  
 1   Flag_Richiesta_Estinzione_cc         377369 non-null  object 
 2   Imp_Valore_del_Cliente               377369 non-null  float64
 3   Flag_Apertura_Conto_Online           377369 non-null  int64  
 4   Flag_Possesso_piu_Conti              377369 non-null  int64  
 5   Eta                                  377362 non-null  float64
 6   Provincia_Domicilio                  356181 non-null  object 
 7   Provincia_Residenza                  357897 non-null  object 
 8   Anno_Apertura_primo_Conto            377369 non-null  float64
 9   Professione                          341172 non-null  object 
 10  Imp_Reddito                          157476 non-null  object 
 11  Tipologia_Cli

In [7]:
# check for missing values
df.isnull().sum()

Id_Cliente                                  0
Flag_Richiesta_Estinzione_cc                0
Imp_Valore_del_Cliente                      0
Flag_Apertura_Conto_Online                  0
Flag_Possesso_piu_Conti                     0
Eta                                         7
Provincia_Domicilio                     21188
Provincia_Residenza                     19472
Anno_Apertura_primo_Conto                   0
Professione                             36197
Imp_Reddito                            219893
Tipologia_Cliente                           0
Sesso                                       7
Profilo_MIFID                           49257
Imp_Canone_Pricing_cc                   27396
Imp_Bonifici_vs_Competitors            288655
Imp_Bonifici_vs_No_Competitors         176679
Num_Utenze_in_essere                   167432
Flag_Accredito_Stipendio                    0
Imp_Spending_Carta_Credito             164706
Imp_Spending_Bancomat                  176004
Num_Accessi_Sito                  

In [8]:
# display the statistical summary of the numerical features
df.describe()

Id_Cliente  Imp_Valore_del_Cliente  Flag_Apertura_Conto_Online  \
count  377369.000000           377369.000000               377369.000000   
mean   277680.735847              644.662654                    0.234230   
std    160279.531097             2928.725757                    0.423517   
min         2.000000                0.000000                    0.000000   
25%    138834.000000               46.870000                    0.000000   
50%    277965.000000               97.270000                    0.000000   
75%    416378.000000              370.320000                    0.000000   
max    555150.000000           377934.870000                    1.000000   

       Flag_Possesso_piu_Conti            Eta  Anno_Apertura_primo_Conto  \
count            377369.000000  377362.000000              377369.000000   
mean                  0.071818      46.039890                2004.805750   
std                   0.258187      13.146689                   3.288509   
min                   0.000000       3.000000                1994.000000   
25%                   0.000000      37.000000                2002.000000   
50%                   0.000000      43.000000                2005.000000   
75%                   0.000000      54.000000                2008.000000   
max                   1.000000     132.000000                2010.000000   

       Imp_Canone_Pricing_cc  Imp_Bonifici_vs_Competitors  \
count          349973.000000                 8.871400e+04   
mean                0.903291                 3.183130e+03   
std                 1.825685                 1.423111e+04   
min                 0.000000                 1.000000e-02   
25%                 0.000000                 1.575825e+02   
50%                 0.000000                 4.790000e+02   
75%                 0.325000                 1.500000e+03   
max                 5.950000                 1.100000e+06   

       Imp_Bonifici_vs_No_Competitors  Num_Utenze_in_essere  ...  \
count                    2.006900e+05         209937.000000  ...   
mean                     3.352734e+03              4.454517  ...   
std                      1.511987e+04              3.636854  ...   
min                      1.000000e-02              1.000000  ...   
25%                      3.500000e+02              2.000000  ...   
50%                      8.058555e+02              3.000000  ...   
75%                      2.047996e+03              6.000000  ...   
max                      1.130700e+06             40.000000  ...   

       Imp_Liquidità_Attuale  Imp_Gestito_attuale  Imp_Amministrato_attuale  \
count           3.773640e+05         1.111880e+05              1.876340e+05   
mean            1.513478e+04         6.770461e+04              7.614477e+04   
std             5.204623e+04         1.940914e+05              2.669638e+05   
min            -2.998609e+06         0.000000e+00              0.000000e+00   
25%             6.292100e+02         7.880375e+03              4.966840e+03   
50%             3.850860e+03         2.329358e+04              2.084153e+04   
75%             1.417872e+04         6.469545e+04              6.766876e+04   
max             1.686020e+07         1.736378e+07              4.808764e+07   

       Imp_Liquidità_Attuale_6m  Imp_Gestito_attuale_6m  \
count              3.773560e+05            1.109000e+05   
mean               1.532084e+04            6.554481e+04   
std                5.201275e+04            1.780930e+05   
min               -2.990061e+06            0.000000e+00   
25%                6.313775e+02            7.808850e+03   
50%                3.788385e+03            2.284953e+04   
75%                1.397786e+04            6.297351e+04   
max                1.486619e+07            1.838148e+07   

       Imp_Amministrato_attuale_6m  Flag_Trasferimento_Titoli_Out  \
count                 1.862980e+05                  377369.000000   
mean                  7.233862e+04                       0.008358   
std                   2.63

In [19]:
# display the unique values
df['Flag_Richiesta_Estinzione_cc'].unique()

array(['no', 'si'], dtype=object)

In [20]:
# display the unique values
df['Flag_Apertura_Conto_Online'].unique()

array([0, 1], dtype=int64)

In [14]:
# display the unique values
df['Eta'].unique()

array([ 38.,  45.,  61.,  33.,  36.,  48.,  51.,  44.,  63.,  32.,  66.,
        57.,  60.,  40.,  49.,  31.,  35.,  46.,  42.,  50.,  37.,  41.,
        39.,  47.,  71.,  77.,  54.,  70.,  24.,  78.,  55.,  58.,  30.,
        29.,  43.,  56.,  64.,  76.,  59.,  65.,  86.,  72.,  73.,  53.,
        81.,  62.,  68.,  34.,  74.,  27.,  26.,  28.,  79.,  69.,  19.,
        52.,  75.,  67.,  23.,  25.,  22.,  87.,  21.,  82.,  80.,  83.,
        85.,  91.,  97.,  84.,  90.,  89.,  20.,  94.,  88.,  18.,  92.,
        93.,  16.,  17.,  13., 102.,  99.,  96.,   5.,  11., 101.,  14.,
       132., 105.,  95.,  98.,  10.,   3.,   9., 100.,   7.,  nan,  12.,
         4.,   6.,   8.,  15.])

In [15]:
# display the unique values
df['Provincia_Domicilio'].unique()

array(['BO', 'SA', 'VT', 'MI', 'AL', 'NO', 'BZ', 'MO', 'CT', 'RN', 'RE',
       'FI', 'AV', 'PN', 'TR', 'GE', 'VI', 'FR', 'FM', 'CR', 'RM', nan,
       'TO', 'PD', 'CA', 'CE', 'SR', 'BI', 'PI', 'CO', 'CB', 'MN', 'PU',
       'AR', 'PA', 'TE', 'MB', 'VA', 'SP', 'BS', 'RA', 'CI', 'PV', 'FE',
       'LU', 'PR', 'PT', 'UD', 'MC', 'FG', 'LT', 'BA', 'PO', 'TA', 'LC',
       'VE', 'TP', 'PG', 'SI', 'TN', 'GO', 'TV', 'BG', 'MS', 'CH', 'VR',
       'FC', 'LI', 'GR', 'LE', 'VC', 'OR', 'LO', 'EE', 'AQ', 'SV', 'RC',
       'RG', 'SS', 'CS', 'PZ', 'AT', 'ME', 'CL', 'BR', 'MT', 'RO', 'TS',
       'PC', 'CN', 'AG', 'RI', 'PE', 'CZ', 'IM', 'AP', 'AN', 'BT', 'VS',
       'NU', 'BL', 'OT', 'OG', 'BN', 'VB', 'IS', 'AO', 'SO', 'EN', 'KR',
       'VV', 'PS', 'FO', '8N', 'BE'], dtype=object)

In [16]:
# display the unique values
df['Provincia_Residenza'].unique()

array(['BO', 'SA', 'VT', 'MI', 'AL', 'NO', 'BZ', 'MO', 'CT', 'RN', 'RE',
       'FI', 'AV', 'PN', 'TR', 'GE', 'VI', 'FR', 'FM', 'CR', 'RM', nan,
       'TO', 'PD', 'CA', 'CE', 'SR', 'BI', 'PI', 'CO', 'FC', 'CB', 'MN',
       'PU', 'BN', 'AR', 'PA', 'TE', 'MB', 'VA', 'BS', 'RA', 'CI', 'PV',
       'FE', 'LU', 'PR', 'PT', 'TS', 'MC', 'FG', 'LT', 'BA', 'PO', 'TA',
       'LC', 'GR', 'VE', 'TP', 'PG', 'SI', 'TN', 'GO', 'UD', 'TV', 'BG',
       'MS', 'CH', 'VR', 'LI', 'LE', 'VC', 'SP', 'SS', 'OR', 'LO', 'AQ',
       'CN', 'RC', 'RG', 'RO', 'CS', 'PZ', 'AT', 'ME', 'CL', 'SV', 'BR',
       'MT', 'PC', 'PE', 'AG', 'RI', 'CZ', 'IM', 'AP', 'AN', 'BT', 'VS',
       'NU', 'BL', 'OT', 'OG', 'VB', 'EE', 'AO', 'IS', 'SO', 'EN', 'KR',
       'VV', 'PS', 'FO'], dtype=object)

In [11]:
# display the unique values
df['Anno_Apertura_primo_Conto'].unique()

array([2004., 2000., 2005., 2010., 2001., 2008., 2002., 2007., 2003.,
       2006., 2009., 1999., 1994., 1995., 1998., 1996., 1997.])

In [9]:
# display the unique values
df['Professione'].unique()

array(['Impiegato', 'Altro/Nessuno', 'Quadro', 'Operaio', nan,
       'Ufficiale/Sottufficiale',
       'Libero professionista/Titolare di impresa', 'Dirigente',
       'Commercialista', 'Rappresentante/Agente', 'Ingegnere/Architetto',
       'Avvocato', 'Medico/Farmacista', 'Autotrasportatore',
       'Docente/Insegnante', 'Commesso/Ausiliario',
       'Ufficiale/Sottoufficiale',
       'Libero professionista/Titolare impresa', 'Notaio'], dtype=object)

In [21]:
# display the unique values
df['Imp_Reddito'].unique()

array(['Medio (tra 1500 e 1800)', 'Alto (tra 1800 e 2500)',
       'Basso (tra 1200 e 1500)', nan, 'Altissimo (>2500)',
       'Bassissimo (<1200)'], dtype=object)

In [22]:
# display the unique values
df['Tipologia_Cliente'].unique()

array(['Investor', 'Trader', 'ActiveTrader', 'Banker', 'Sleeper'],
      dtype=object)

In [12]:
# display the unique values
df['Profilo_MIFID'].unique()

array(['PRUDENTE', 'BILANCIATO', 'DINAMICO', nan, 'ND', 'CAUTO'],
      dtype=object)

In [13]:
# display the unique values
df['Var_Numero_Utenze'].unique()

array([  0.,   1.,  -1.,  nan,   2.,  -4., -23.,  -8.,  -5.,  -2.,  -7.,
        -6.,  -3.,   3., -11.,   4.,   5.,  15.,   7.,   6.,   8.,  10.,
        11.,  12., -14., -10.,   9.,  -9.,  16., -12.,  14., -13.,  22.,
        18., -16., -15.,  13.,  17.,  19., -17.,  21.,  20., -26.,  25.])

In [17]:
# check the value percentages for the 'Provincia_Domicilio' column
df.Provincia_Domicilio.value_counts(normalize=True)

RM    0.147911
MI    0.088186
TO    0.056567
BS    0.029061
GE    0.023951
        ...   
OG    0.000143
FO    0.000081
PS    0.000073
8N    0.000003
BE    0.000003
Name: Provincia_Domicilio, Length: 114, dtype: float64

In [18]:
# check the value percentages for the 'Provincia_Residenza' column
df.Provincia_Residenza.value_counts(normalize=True)

RM    0.140691
MI    0.081266
TO    0.055709
BS    0.029042
GE    0.024074
        ...   
EE    0.000673
VS    0.000584
OG    0.000193
PS    0.000006
FO    0.000003
Name: Provincia_Residenza, Length: 112, dtype: float64

In [ ]:
# TO MODIFY THE CELL BELOW

In [ ]:
# define different typologies of variables
continuous_vars = ['pax_total', 'pax_1', 'pax_2', 'pax_3', 'pax_4', 'pax_5', 'pax_6', 'load_factor', 'baggage_weight',
                   'mail_weight', 'temperature', 'relative_humidity', 'apparent_temperature', 'precipitation',
                   'wind_speed']

discrete_vars = ['date', 'month', 'day', 'weekday', 'hour']

ordinal_vars = []

nominal_vars = ['terminal_num', 'airline_code', 'airline_name', 'aircraft_type_code', 'aircraft_type_name',
                'service_type', 'country_name', 'flight_number', 'main_delay_code', 'source_delay', 'runway',
                'spot_number', 'weather_code']

binary_vars = ['departing', 'domestic', 'cancelled', 'regular', 'CIS_country']

quant_vars = continuous_vars + discrete_vars

categ_vars = ordinal_vars + nominal_vars + binary_vars

delay = ['delayed']


## Exporting the database tables

The 11 tables will be exported as **CSV** files, which will be used to create a semantic model in **Power BI** and related dashboards in the next step.  
  
  <br/><br/>